### PR TITLE
gentl: Fix zlib path for Linux systems

### PR DESCRIPTION
**Pull request by danielmeer**
I tried to compile the code on an ARM system with Linux and ran in some issues.

After running `cmake`, I got this warning:

> WARNING: Target "gstgentl" requests linking to directory "/usr/include/gstreamer-1.0".  Targets may link only to libraries.  CMake is dropping the item.

And after running `make`, I got this error:

> make[2]: *** No rule to make target '/usr/include/gstreamer-1.0/../../lib/z.lib', needed by 'sys/gentl/libgstgentl.so'.  Stop.
> make[1]: *** [CMakeFiles/Makefile2:457: sys/gentl/CMakeFiles/gstgentl.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2

This pull-request fixes the issue. There were actually two problems with the library path:

1. On Linux, the library is called libz.so instead of z.lib

2. On multiarch systems, the library may be in another location than /usr/lib/ (e.g. in a subfolder)

By only specifying the library name we ask the linker to find the library. I don't have enough experience with CMake to know whether this is good or bad practice. This should also work on Windows, but I haven't tested that.

### CODE REVIEW

**Comment by mrstecklo** [comment]
Hi, @danielmeer
It is better use `find_library` in this case

``` cmake
find_library(ZLIB
    NAMES z
    HINTS
        ${GSTREAMER_INCLUDE_DIR}/../../lib/
)

target_link_libraries(
    ...
    ${ZLIB}
)
```
This way you can specify additional search paths in `HINTS` section. `find_library` also serches in default directories like `/usr/lib` and probably `/usr/lib/<platform>`. [CMake doc](https://cmake.org/cmake/help/latest/command/find_library.html?highlight=find_library)

**Comment by joshdoe** [comment]
Try out my branch [joshdoe:fix-gentl-on-linux](https://github.com/joshdoe/gst-plugins-vision/tree/fix-gentl-on-linux), works for me on Windows too. Got rid of FindZLIB.cmake in repository, uses CMake available find module, and on Windows defaults to using the GStreamer provided ZLIB. If it works feel free to modify this PR to match and I'll merge.

**Comment by danielmeer** [comment]
Thanks, your commit fixes the issue on Linux as well.

I'm not sure what's the proper workflow on GitHub, so I just changed the pull-request to include your commit instead.

However, I noticed compiling gentl on Linux is still broken because of a recent commit on master (which includes Windows.h and uses a Windows-specific type). But I'll create a new issue for that.

**Comment by danielmeer** [comment]
The new issue is here: #71

**Comment by joshdoe** [comment]
Sorry for the delay, merging this now.

**Pull request merged**
