### PR TITLE
pylonsrc: Corrupt frames / rebased

### PR DESCRIPTION
**Pull request by mrstecklo**
Here are the changes made in [#32](https://github.com/joshdoe/gst-plugins-vision/pull/32) by @AB-Eskild. I've rebased them on top of my changes, as there were a lot of refactoring and merge conflicts are nontrivial.
Thanks again to @AB-Eskild. Hope to see his work being helpful to others

### CODE REVIEW

**Comment by joshdoe** [comment]
Thanks. I'm not a big fan of the property name `failrate`, as it's not a rate, but I don't feel too strongly about it, and don't have a perfect replacement suggestion. If you happen to have a better name and feel like changing it, go ahead, otherwise let me know and I'll just merge it as is.

**Comment by mrstecklo** [comment]
Maybe something like `retrylimit` or `framedroplimit`

**Comment by mrstecklo** [comment]
It's difficult for me to judge as I'm not native speaker

**Comment by joshdoe** [comment]
Both of those are good suggestions, but maybe like `framedroplimit` better. I can refactor to use `framedroplimit` if you'd like, or you can, let me know. Thanks.

As an aside, I've been used to seeing property names in GStreamer with `-` separating words, but we have so many properties in this element we may as well leave them as is, or make it as part of a big refactor PR if anyone cares enough to do so.

**Comment by mrstecklo** [comment]
I've renamed `failrate` to `frame-drop-limit`. And separated words in other new property names with dash. Also squashed second commit (originally [1a68796](https://github.com/joshdoe/gst-plugins-vision/pull/32/commits/1a68796e1e4ab516061f823c7939971745613d94))

**Pull request merged**
